# Generated by Django 3.0.2 on 2020-02-25 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fk_id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeportesUY.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('fechaNacimiento', models.DateField()),
                ('mail', models.CharField(max_length=40)),
                ('sexo', models.CharField(max_length=1)),
                ('cedula', models.CharField(max_length=8)),
                ('contrasena', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=50)),
                ('fk_id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeportesUY.Categoria')),
                ('fk_id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeportesUY.Equipo')),
                ('fk_id_tipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeportesUY.TipoUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='Velocidad',
            fields=[
                ('id_velocidad', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeportesUY.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id_estadistica', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeportesUY.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='capacidadDeSaltoVertical',
            fields=[
                ('id_capacidadsaltovertical', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeportesUY.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Alcance',
            fields=[
                ('id_alcance', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeportesUY.Usuario')),
            ],
        ),
    ]
